### PR TITLE
[WIP] Customizable naming rules

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
There are still couple of test failing:  all tests testing suppression, + APs + UoMs,  + few  other cases. 

Change in configuration schema is breaking, not sure if it's acceptable.

### CODE REVIEW

**Comment by duckmatt** [comment]
Looks good, thanks for taking the time to do this. Don't worry about breaking changes to the config schema

**Comment by duckmatt** [comment]
I've started updating the tests on https://github.com/fsprojects/FSharpLint/tree/naming_rules

**Comment by duckmatt** [comment]
Thanks very much, I've included the changes in 0.6.1-beta

**Comment by forki** [comment]
💋

**Pull request merged**
