### PR TITLE
add nuget package for api only

### PR DESCRIPTION
**Pull request by jmecosta**
suppose this is also useful for you.

### CODE REVIEW

**Comment by duckmatt** [comment]
thanks, this is useful

**Comment by jmecosta** [comment]
No prob. Thanks also

**Comment by duckmatt** [comment]
The api package is on nuget now here: http://www.nuget.org/packages/FSharpLint.Core/

The [api has changed a bit](https://github.com/fsprojects/FSharpLint/blob/master/src/FSharpLint.Application/Lint.fsi) and included functions to deal with getting and loading configuration files

**Comment by jmecosta** [comment]
Ok thanks for the notice, I try to upgrade as soon as I have a bit of free
time. But anyway the overloaded functions to run lint are still there?

**Comment by jmecosta** [comment]
Ok I see that it did, will take look

**Comment by jmecosta** [comment]
works great, thanks.

**Pull request merged**
