### PR TITLE
Add FavourNonMutablePropertyInitialization rule

### PR DESCRIPTION
**Pull request by webwarrior-ws**
Add FavourNonMutablePropertyInitialization rule and tests for it.
Apply suggestions of this rule to FSharpLint code.

Supersedes https://github.com/fsprojects/FSharpLint/pull/662

Fixes https://github.com/fsprojects/FSharpLint/issues/535

### CODE REVIEW

**Comment by knocte** [comment]
Please squash a36ff properly.

**Comment by webwarrior-ws** [comment]
> Please squash a36ff properly.

done

**Comment by knocte** [comment]
Let's also squash d18acf751e84905f92a6dd656962636d91ef6b01, otherwise all commits' CI status will be red except the last one.

**Comment by webwarrior-ws** [comment]
> Let's also squash [d18acf7](https://github.com/fsprojects/FSharpLint/commit/d18acf751e84905f92a6dd656962636d91ef6b01), otherwise all commits' CI status will be red except the last one.

Done

**Pull request merged**
