### PR TITLE
Update to FCS 36.0.1

### PR DESCRIPTION
**Pull request by baronfel**
These commits update to FCS 36.0.1. The biggest change from FSharpLint's perspective is the addition of the SynType.Paren node, which was easy to add support for.  The AST forms returned in certain cases also changed as a result of this, and so some test baselines were updated, and a rule had to learn to check one of the new forms.

### CODE REVIEW

**Comment by jgardella** [comment]
Awesome, thanks @baronfel! I will push out a release with these changes.

What does the `SynType.Paren` node represent that we didn't have before?

**Comment by baronfel** [comment]
@auduchinok added it recently, it tracks data around explicitly-parenthesized expressions:

> Keeps parser knowledge about (possibly nested) parens found when parsing syntax types. It's needed when trying to get tree structures in cases like the following:

```fsharp
type A = int * (int * int)
type B = (int -> int) -> int
type C = ((int))
```

and it also wraps prefix operator function calls from what I can tell.

**Comment by auduchinok** [comment]
@baronfel The prefix operator uses was a different PR but generally you're correct.

**Comment by baronfel** [comment]
Oh I forgot to mention the other feature: it gives me headaches when updating fantomas!

**Pull request merged**
