### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
New version of FCS was released.

### CODE REVIEW

**Comment by duckmatt** [comment]
thank you

**Comment by Krzysztof-Cieslak** [comment]
Any chance to get NuGet release with those changes? I'm trying to update FSAC to latest FCS :-)

**Comment by duckmatt** [comment]
yep, uploaded release [0.7.3-beta](https://www.nuget.org/packages/FSharpLint.Core/0.7.3-beta) :)

**Comment by Krzysztof-Cieslak** [comment]
Thanks :)

**Pull request merged**
