### PR TITLE
add .net standard 2.0 support

### PR DESCRIPTION
**Pull request by enricosada**
remove (for the `netstandard2.0` tfm) the api based on projectcracker (old fsproj), because is not supported on netstandard.

the failing test are disabled, with category `NetstandardKnownFailure`
You can run these with:

```
dotnet test tests\FSharpLint.Core.Tests.netstandard --filter TestCategory=NetstandardKnownFailure
```

### CODE REVIEW

**Comment by enricosada** [comment]
ok @duckmatt ready to review

**Comment by duckmatt** [comment]
Great, thank you for taking the time to do this :) do you know what causes the `NetstandardKnownFailure` tests fail?

**Comment by enricosada** [comment]
Nope, sry.
i tried to check a bit, but i am not familiar with this lib, so dunno if real error or just FCS who diverge on stuff

**Comment by enricosada** [comment]
@duckmatt is possibile to have a new release? i'd like to use this with netstandard in https://github.com/fsharp/FsAutoComplete/pull/224

atm i am using a dev build and works, but i am near merge :D

**Comment by duckmatt** [comment]
Sorry for the slowness, I've released [0.9.0-beta](https://www.nuget.org/packages/FSharpLint.Core/0.9.0-beta), I'll try to take a look at the excluded tests this weekend to remove the beta tag :)

**Comment by ErikSchierboom** [comment]
@duckmatt I see that the 0.9.0-beta package is still the latest version. Might I inquire on the progress of the netstandard version?

**Comment by duckmatt** [comment]
@ErikSchierboom I have to admit I haven't touched it since. I'm going to try and allocate a bit more of my time back to this project so should be able to release a 0.9.1 with updated dependencies and fixed build in the next week or so

**Comment by ErikSchierboom** [comment]
@duckmatt Great! Good luck with it.

**Pull request merged**
