### PR TITLE
Add new rule FavourSingleton

### PR DESCRIPTION
**Pull request by su8898**
Fixes https://github.com/fsprojects/FSharpLint/issues/526

### CODE REVIEW

**Comment by duckmatt** [comment]
I think it may be possible to express this as one of the hints, although I'm not averse to an additional rule either. Trade off is the rule is easier to ignore one rule specifically, but adding an additional hint should have better performance over an additional rule

(Also apologies, just merged in another PR so needs conflicts resolved)

**Comment by knocte** [comment]
Disadvantages of converting this into a hint:
1. Can't be disabled by default (and I've already known 2 people which don't like this rule).
2. There's already a hint that recommends you to use [x] instead of x::[], so fixing this hint might lead to yet another hint, unless we change that hing to recommend a Singleton func, but should we? (See 1. :) )

**Comment by knocte** [comment]
> ...just merged in another PR so needs conflicts resolved)

No worries, I'll rebase myself soon.

**Comment by knocte** [comment]
Superseded by https://github.com/fsprojects/FSharpLint/pull/587

**Pull request closed without merging**
