### PR TITLE
Update FCS to 11.0.4

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
Fast NuGet release would be appreciated :)

### CODE REVIEW

**Comment by duckmatt** [comment]
thank you, [package on nuget](https://www.nuget.org/packages/FSharpLint.Core/0.7.4-beta)

**Comment by Krzysztof-Cieslak** [comment]
Perfect, thanks a lot :)

**Comment by duckmatt** [comment]
No problem, would it be helpful if I add you to the project so you're also able to release updates? Updating the release notes on master now triggers a deploy to nuget via appveyor

**Comment by Krzysztof-Cieslak** [comment]
Sounds good to me, I'll only do FCS updates if necessary.

**Pull request merged**
