### PR TITLE
Rule to recommend not to use the pipe operator if it's only used once 

### PR DESCRIPTION
**Pull request by tehraninasab**
Fixes https://github.com/fsprojects/FSharpLint/issues/594

### CODE REVIEW

**Comment by knocte** [comment]
I've realised that this is going too far and the rule is going to raise too many warnings.

Let's have this new test:
```
let someFunc someParam =
    someOtherFunc1 someParam
    |> someOtherFunc2
```

And the rule should not give errors for the above, even if the pipe operator is only used once. Why? Because the alternative would be `someOtherFunc2 (someOtherFunc1 someParam)`, and using the operator in this case is avoiding the use of parentheses, which is fair enough.

BTW let's rename the rule to AvoidOnePipeOperator, to make it crystal clear that multiple pipes are fine.

**Comment by realmarv** [comment]
> I've realised that this is going too far and the rule is going to raise too many warnings.
> 
> Let's have this new test:
> 
> ```
> let someFunc someParam =
>     someOtherFunc1 someParam
>     |> someOtherFunc2
> ```
> 
> And the rule should not give errors for the above, even if the pipe operator is only used once. Why? Because the alternative would be `someOtherFunc2 (someOtherFunc1 someParam)`, and using the operator in this case is avoiding the use of parentheses, which is fair enough.
> 
> BTW let's rename the rule to AvoidOnePipeOperator, to make it crystal clear that multiple pipes are fine.

Added the test and fixed the rule to pass it. But, the name of the rule is already AvoidOnePipeOperator

**Comment by knocte** [comment]
> But, the name of the rule is already AvoidOnePipeOperator

Sorry, I meant `AvoidSinglePipeOperator`.

**Comment by knocte** [comment]
Why is CI red?

**Pull request merged**
