### PR TITLE
Fix error linting projects that use .NET Framework

### PR DESCRIPTION
**Pull request by webwarrior-ws**
* Upgrade Ionide.ProjInfo to 0.58.0 (needed to bring the fix for parsing legacy projects, upstream PR: https://github.com/ionide/proj-info/pull/131 , upstream commit: https://github.com/ionide/proj-info/commit/3542cee96562b1e64c20a6b88278b1a8346d83f3 ).
* Upgrade FSharp.Compiler.Service to version 41 (needed because the new Ionide.ProjInfo version, depends on a higher version of F.C.S.).
* Made changes to framework, rules and test framework code necessary to accomodate API changes in this version 41.x of FCS compared to version 40.

Fixes https://github.com/fsprojects/FSharpLint/issues/336

### CODE REVIEW

**Comment by knocte** [comment]
> Upgrade FSharp.Compiler.Service to version 41.

Please explain why this is needed.

> Upgrade Ionide.ProjInfo to 0.58.0.

Please explain why this is needed.

**Comment by knocte** [comment]
> Upgrade FCS to version 41 and Ionide.ProjInfo to 0.58.0

Title of PR should reflect the goal of the PR, not its implementation details.

**Comment by webwarrior-ws** [comment]
> > Upgrade FSharp.Compiler.Service to version 41.
> 
> Please explain why this is needed.
> 
> > Upgrade Ionide.ProjInfo to 0.58.0.
> 
> Please explain why this is needed.

Ionide.ProjInfo upgrade is needed to fix https://github.com/fsprojects/FSharpLint/issues/336.
FSharp.Compiler.Service upgrade is needed because of Ionide.ProjInfo upgrade.

**Comment by knocte** [comment]
> Ionide.ProjInfo upgrade is needed...

I'm not asking you to explain it to me, because I already know (and I know you know). I'm asking you to edit the PR description.

**Comment by knocte** [comment]
> Fix error linting projects that use newer .NET versions

Newer .NET versions??? Please read the github issue first.

**Comment by webwarrior-ws** [comment]
Weren't there several issues that required new Ionide.ProjInfo? I remember testing on .NET 6 project.

**Comment by knocte** [comment]
> Weren't there several issues that required new Ionide.ProjInfo? I remember testing on .NET 6 project.

We didn't confirm that new versions of Ionide.ProjInfo fixed other problems. But you did confirm that it fixed issue #336, so that reason alone (only it) is enough to merge this PR.

**Pull request merged**
