### PR TITLE
Improve "Remove broken link from readme"

### PR DESCRIPTION
**Pull request by knocte**
This improves commit 62e181d7fde15ff6cbd4a52c8bf4fb29e9ac0a96 by
using this technique:

https://stackoverflow.com/a/7335259/1623521

### CODE REVIEW

**Comment by duckmatt** [comment]
Ah nice, thank you

**Comment by knocte** [comment]
Actuallly it doesn't work 😭 so it needs to be reverted

**Comment by knocte** [comment]
Unless you need to do something to update the docs website? not sure

**Comment by duckmatt** [comment]
Ah sorry, I think I forgot to reply on the previous PR, the docs do currently get pushed on release (via tag), I'll have a look at pushing that shortly

**Comment by knocte** [comment]
Ah great sounds good.

**Pull request merged**
