### PR TITLE
Bugfix/outdated

### PR DESCRIPTION
**Pull request by milbrandt**
remove outdated doku and resourc

### CODE REVIEW

**Comment by milbrandt** [comment]
lots of md files contain hard tabs, even on F# code samples, and trailing white space. I didn't change here, would be willing to fix them if you don't mind.

**Comment by witoldsz** [comment]
Please merge it, broken links are so… unpleasant :)

**Comment by duckmatt** [comment]
Great work, thank you. Sorry for the slow merge!

**Comment by milbrandt** [comment]
@duckmatt No Problem, I'm happy to help and the Sonar-F# Plugin is relying on your work.

What's about my question on tabs and whitespaces in the docu (see comment above)? 
As I observed further inconsistencies in docu , I will create a PR for these anyway.

**Pull request merged**
